### ISSUE TITLE
the read and write registers doesn't work !!

### ISSUE THREAD

**Issue by alirezaahmadi** [GEPSE/STM32_NRF24#1]

**Comment by nesvera** [comment]
Hello Alireza, can you explain to me more about the problem you found?

**Comment by alirezaahmadi** [comment]
actually there wasn't a problem with those two functions. I am new with STM32 , but, the main problem was related to pin assignment (CE and CSN). for using your released code, the user had to set the pins as output manually, but I was expected that it does it automatically through the pin assignments which was done in first of your example codes. I have written a function to complete the operation. everything is fine now... 
thank you so much...

**Comment by nesvera** [comment]
😄
